[package]
name = "totient-function"
version = "0.1.0"
authors = ["Polochon-street <polochonstreet@gmx.fr>"]
edition = "2018"

[dependencies]
num = "0.2"

[package.metadata.rosettacode]
url = "https://rosettacode.org/wiki/Totient_function"
